### ISSUE TITLE
I can not create a configuration file.

### ISSUE THREAD

**Issue by ArtemProkopenko** [srtfisher/laravel-elastica#1]
Hi, dear.

I try use command from readme: php artisan config:publish srtfisher/laravel-elastica, but get the message: "[InvalidArgumentException] Configuration not found."

**Comment by srtfisher** [comment]
Did you add this line to your `app/config/app.php` file under service providers?

```
'Srtfisher\LaravelElastica\LaravelElasticaServiceProvider'
```
